# -*- after-save-hook: (org-babel-tangle); before-save-hook: (delete-trailing-whitespace)-*-

#+PROPERTY: header-args:latex :exports code :results none :tangle resume.tex

* Preamble

  #+begin_src latex
    % !TEX TS-program = lualatex

    \documentclass[alternative,10pt,compact]{yaac-another-awesome-cv}
  #+end_src

** Settings

   #+begin_src latex
     \name{Jonathan}{Jin}
     \tagline{Machine Learning Infrastructure Engineer}
     \socialinfo{
       \website{https://jonathanj.in}{jonathanj.in}
       \email{me@jonathanj.in}
       \linkedin{jinnovation}
       \github{jinnovation}
     }
   #+end_src

** Overrides + Patches

   Some of the upstream styling isn't to my personal liking, so we'll override
   some of that in this section.

*** Header overrides

    Upstream, the name header bolds and smallcaps the last name, which I'm not a
    huge fan of. We'll set it to simply bolden the name, increase the text size,
    and color it w/ the "accent color" defined upstream.

    Similarly, the subtitle that contains the "tagline" is also formatted with
    the accent color as well as bolded, which I'm not a fan of. We'll set it
    here to simply be large text.

    #+begin_src latex
      \renewcommand\user[2]{\color{accentcolor}{\LARGE\textbf{#1 #2}}\color{Black}}

      \renewcommand\resumetitle[1]{
        %% \ifundef{\@alternative}{
        %%    \par{
        %%    	 \bigskip\center{\Large \color{accentcolor}\textbf{#1}\color{Black}}\par
        %%    }
        %%    \bigskip
        %% }{
          \large{#1}
        %% }
      }
    #+end_src

*** Dimensions

    Something about how upstream specifies the width of the "right column" --
    which contains the job titles and associated bullet points -- is a little
    off. As a result, text flows past the header horizontal line rule, which
    isn't a good look. We manually compensate here.

    #+begin_src latex
      \setleftcolumnlength{1.5cm}
      \setlength{\rightcolumnlength}{\dimexpr(\rightcolumnlength-0.5cm)\relax}

    #+end_src

** Extensions

*** Experience entries with blurbs

    I'd like to have each entry in the experience section have a "blurb"
    providing high-level overview of the nature of the work, e.g. team and
    organization and general focus areas. This command is a copy-paste of the
    upstream =\experience= with an additional field to that effect.

    #+begin_src latex
      \newcommand\experiencewithblurb[8]{
        #1    & \textbf{\accentcolor{#2}} \textsc{#3} \hfill #4   \\*
        #5    & \textit{#6} \\*
              & \begin{minipage}[t]{\rightcolumnlength}
                  #7
                \end{minipage}									\\*
              & \footnotesize{\foreach \n in {#8}{\cvtag{\n}}} 	\\
      }
    #+end_src

*** Icon-less section headers

    #+begin_src latex
      \newcommand\sectionHeader[1]{\section{\texorpdfstring{\color{accentcolor}\textsc{#1}}{#1}}}
    #+end_src

*** Accentuate arbitrary text

    A convenience command to color arbitrary text with the accent color.

    #+begin_src latex
      \newcommand\accentcolor[1]{\color{accentcolor}#1\color{Black}}

    #+end_src

* Content

** Head

   #+begin_src latex
     \begin{document}

     %% cls sets French as the default babel language; we undo that here.
     \selectlanguage{english}

     \makecvheader

     \makecvfooter
         {\textsc{\today}}
         {\textsc{Jonathan Jin}}
         {}

   #+end_src

** Experience

   #+begin_src latex
     \sectionHeader{Experience}

     \begin{experiences}

       \experiencewithblurb
           {Present}
           {Spotify}
           {Senior Machine Learning Software Engineer}
           {New York}
           {03/2021}
           {Member of ML Platform. Working on: centralized, multi-tenant ML
             orchestration infrastructure with Kubernetes and
             \link{http://kubeflow.org/}{Kubeflow}; and user-facing
             pipeline-authoring SDK based on \link{http://tensorflow.org/tfx/}{TFX}.
           }
           {
             \begin{itemize}
             \item Implemented standardized, per-team resource quotas to
               mitigate risk of noisy neighbor effect in centralized Kubeflow
               clusters;
             \item Oversaw comprehensive formalization of SLO-tracking strategy,
               using Terraform to formalize SLOs in
               \link{https://cloud.google.com/stackdriver/docs/solutions/slo-monitoring}{GCP}
               for all clusters in our multi-cluster in reproducible fashion;
             \item Spearheaded development of a custom metrics exporter, transforming
               Kubernetes events into actionable Prometheus metrics to address gaps
               in our observability/reliability strategy.
             \end{itemize}
           }
           {TensorFlow, TFX, Kubernetes, Kubeflow, GCP, Terraform, Prometheus, gRPC}

       \emptySeparator

       \experiencewithblurb
           {01/2021}
           {NVIDIA}
           {Senior Systems Software Engineer, AI Infrastructure}
           {New York}
           {12/2019}
           {Member of AI Infrastructure. Contributor to
             \link{https://blogs.nvidia.com/blog/2018/09/13/how-maglev-speeds-autonomous-vehicles-to-superhuman-levels-of-safety/}{MagLev},
             NVIDIA’s AI infrastructure for autonomous vehicle development. Also
             contributed to Modulus, the deep learning SDK for autonomous vehicle
             R\&D.}
           {
             \begin{itemize}
             \item Initiated development of solution for ``hybrid data/model
               parallelism'' using a Ray-based parameter server design and Horovod to
               enable horizontally-scalable multi-task training;
             \item Co-delivered a Kubernetes-based scheduling mechanism to enable
               priority access to cluster resources for select use cases, e.g. prep for
               upcoming external demos, via virtual ``resource shares'';
             \item Authored self-service, reproducible, and traceable workflows to
               generate ``miniaturized'' production datasets, enabling rapid
               iteration/prototyping of training infrastructure refinements
             \end{itemize}
           }
           {Kubernetes, TensorFlow, Horovod, Ray, gRPC, Bazel, SwiftStack}

       \emptySeparator

       \experiencewithblurb
           {12/2019}
           {Twitter}
           {Machine Learning Software Engineer}
           {New York}
           {08/2018}
           {Member of \link{http://cortex.twitter.com}{Cortex}, Twitter's central ML
             platform organization. Worked on: workflow orchestration; experiment
             management/iteration; and overall ML engineering productivity.}
           {
             \begin{itemize}
             \item
               Spearheaded initial integration of
               \link{http://tensorflow.org/tfx/}{TensorFlow Extended (TFX)} with
               \link{https://blog.twitter.com/engineering/en_us/topics/insights/2018/ml-workflows.html}{legacy
                 Airflow-based orchestration platform} to increase agility of
               workflow development, iterative execution/experimentation, etc.
             \item
               Enabled distributed training of TensorFlow models in Apache Mesos from
               an Airflow pipeline via
               \link{https://blog.twitter.com/engineering/en_us/topics/insights/2018/twittertensorflow.html}{Deepbird},
               Twitter’s TensorFlow-based model training/evaluating/serving framework
             \end{itemize}
           }
           {Apache Airflow, Apache Aurora, TensorFlow}

       \emptySeparator

       \experiencewithblurb
           {07/2018}
           {Uber}
           {Software Engineer}
           {New York}
           {07/2016}
           {Member of \link{https://eng.uber.com/observability-at-scale/}{Observability Applications}. Worked on forecasting and anomaly detection for time series metrics.}
           {
             \begin{itemize}
             \item
               Re-architected time-series metric forecasting pipeline to support
               concurrent batch backfilling; reduced asymptotic burden on underlying
               data store by ~90\%
             \item
               Extended M3-based anomaly detection platform to support multiple
               forecasting models; carried out migration to intercommunicating
               services with zero downtime and full backwards compatibility

             \end{itemize}
           }
           {Go, Java, M3, Apache Thrift, Cassandra}

       \emptySeparator

       \experiencewithblurb
           {07/2016}
           {OkCupid}
           {Software Engineer}
           {New York}
           {07/2015}
           {Contributed to backend service development as part of a 10-person backend engineering team.}
           {
             \begin{itemize}
             \item Implemented collaborative filtering for matching between
               prospectively compatible users.
             \end{itemize}
           }
           {C++}
     \end{experiences}

   #+end_src

** Skills

   #+begin_src latex
     \sectionHeader{Skills}

     \begin{keywords}
       \keywordsentry{Programming Languages}
       {
         Python,
         Go,
         Bash,
         C++,
         Java
       }
       \keywordsentry{Machine Learning}
       {
         Kubeflow,
         TensorFlow Extended (TFX),
         TensorFlow
       }
       \keywordsentry{Distributed Systems}
       {
         Kubernetes,
         gRPC
       }
       \keywordsentry{Infrastructure Tooling}
       {
         Bazel,
         Prometheus,
         Grafana,
         M3,
         Cassandra,
         Apache Airflow
       }

       \keywordsentry{Cloud Infrastructure}
       {
         Google Cloud Platform (GCP),
         Terraform
       }
     \end{keywords}

   #+end_src

** Education

   #+begin_src latex
     \sectionHeader{Education}

     \begin{scholarship}
       \scholarshipentry{2015}{\textbf{University of Chicago}, B.S. Computer Science, B.A. Economics}
     \end{scholarship}

   #+end_src

** Speaking
   :PROPERTIES:
   :header-args:latex: tangle: no
   :END:

   #+begin_src latex
     \sectionHeader{Speaking}

     \begin{scholarship}

       \scholarshipentry
           {2021}
           {
             \textbf{\link
               {https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/}
               {KubeCon + CloudNativeCon North America 2021}
             },
             \link
             {https://www.youtube.com/watch?v=KUyEuY5ZSqI}
             {``Scaling Kubeflow for Multi-tenancy at Spotify''}
           }

       \scholarshipentry
           {2019}
           {
             \textbf{\link
               {http://ainyc19.xnextcon.com/}
               {AI NEXTCon, New York}
             },
             ``ML Workflows at Twitter: Lessons Learned''
           }
     \end{scholarship}
   #+end_src

** Writing
   :PROPERTIES:
   :header-args:latex: tangle: no
   :END:

   #+begin_src latex
     \sectionHeader{Writing}

     \begin{scholarship}

       \scholarshipentry
           {2018}
           {
             \textbf{Uber Engineering Blog},
             \link
             {https://eng.uber.com/anomaly-detection/}
             {``Implementing Model-Agnosticism in Uber’s Real-Time Anomaly Detection Platform''}
           }

       \scholarshipentry
           {2018}
           {
             \textbf{Uber Engineering Blog},
             \link
             {http://eng.uber.com/observability-anomaly-detection/}
             {``Engineering a Job-based Forecasting Workflow for Observability Anomaly Detection''}
           }
     \end{scholarship}
   #+end_src

** Tail

  #+begin_src latex
    \end{document}
  #+end_src
